name: CI

on: [push]

jobs:
  build: lint
    runs-on: ubuntu-latest
    steps:
    - name: Python Code Quality and Lint
      uses: ricardochaves/python-lint@v1.1.0
        with:
          use-flake8: true
          use-black: true
          use-mypy: true
