exclude_patterns:
  # Default options
  # https://docs.codeclimate.com/docs/excluding-files-and-folders
  - "config/"
  - "db/"
  - "dist/"
  - "features/"
  - "**/node_modules/"
  - "script/"
  - "**/spec/"
  - "**/test/"
  - "**/tests/"
  - "Tests/"
  - "**/vendor/"
  - "**/*_test.go"
  - "**/*.d.ts"

  # Project specific
  - "**/fixtures/"
  - "**/vendor.in/"
