obs:
    tissue_ontology_term_id:
        region:
            mLN: UBERON:0002509
            Caecum: UBERON:0001153
            Sigmoid: UBERON:0001159
            Transverse: UBERON:0001157
    assay_ontology_term_id: EFO:0009310
    disease_ontology_term_id: PATO:0000461
    cell_type_ontology_term_id:
        cell_type:
            B cell IgA Plasma: CL:0000987
            B cell memory: CL:0000787
            CD8 T: CL:0000625
            gd T: CL:0000798
            Mast: CL:0000097
            ILC: CL:0001065
            Macrophage: CL:0000235
            NK: CL:0000623
            Follicular B cell: CL:0000843
            B cell IgG Plasma: CL:0000985
            Tcm: CL:0000791
            B cell cycling: CL:0000236
            Treg: CL:0000815
            LYVE1 Macrophage: CL:0000235 
            Th1: CL:0000545
            Th17: CL:0000899
            cDC2: CL:0000990
            cycling gd T: CL:0000798
            Monocyte: CL:0000576
            cDC1: CL:0000990
            Activated CD4 T: CL:0000896
            pDC: CL:0000784
            Tfh: CL:0002038
            Lymphoid DC: CL:0000451
            cycling DCs: CL:0000451
    sex: unknown
    ethnicity_ontology_term_id: HANCESTRO:0005
    development_stage_ontology_term_id: HsapDv:0000087
uns:
    version:
        corpora_schema_version: 1.0.0
        corpora_encoding_version: 0.0.1
    title: Distinct microbial and immune niches of the human colon
    contributors:
        - name: Ni Huang
          institution: Sanger Institute
          email: nh3@sanger.ac.uk
    layer_descriptions:
        X: sc.pp.normalise_per_cell(10000), sc.pp.log1p, sc.pp.regress_out, sc.pp.scale
    organism_ontology_term_id: NCBITaxon:9606
    project_name: Distinct microbial and immune niches of the human colon
    project_description: >
        Gastrointestinal microbiota and immune cells interact closely and display regional specificity; however, little is known about
        how these communities differ with location. Here, we simultaneously assess microbiota and single immune cells across the
        healthy, adult human colon, with paired characterization of immune cells in the mesenteric lymph nodes, to delineate colonic
        immune niches at steady state. We describe distinct helper T cell activation and migration profiles along the colon and characterize
        the transcriptional adaptation trajectory of regulatory T cells between lymphoid tissue and colon. Finally, we show
        increasing B cell accumulation, clonal expansion and mutational frequency from the cecum to the sigmoid colon and link this to
        the increasing number of reactive bacterial species.
    project_links:
        - link_url: www.gutcellatlas.org
          link_name: Gut Cell Atlas
          link_type: OTHER
        - link_url: www.gutcellatlas.org
          link_name: Gut Cell Atlas
          link_type: SUMMARY
    publication_doi:  https://doi.org/10.1038/s41590-020-0602-z
