obs:
    tissue_ontology_term_id: UBERON:0002048
    assay_ontology_term_id: EFO:0009899 
    disease_ontology_term_id: PATO:0000461
    cell_type_ontology_term_id:
        CellType:
            Alveolar_Type1: CL:0002062
            Alveolar_Type2: CL:0002063
            B_cells: CL:0000236
            Blood_vessel: UBERON:0001981
            Ciliated: CL:1000271
            DC_1: CL:0000990
            DC_2: CL:0000784
            DC_Monocyte_Dividing: DC_Monoctye_Dividing
            DC_activated: CL:0000451
            DC_plasmacytoid: CL:0000784
            Fibroblast: CL:0000057
            Lymph_vessel: UBERON:0001473
            Macrophage_Dividing: CL:0000235
            Macrophage_MARCOneg: CL:0000235
            Macrophage_MARCOpos: CL:0000235
            Mast_cells: CL:0000097
            Monocyte: CL:0000576
            Muscle_cells: CL:0000187
            NK: CL:0000623
            NK_Dividing: CL:0000623
            Plasma_cells: CL:0000786
            T_CD4: CL:0000624
            T_CD8_CytT: CL:0000794
            T_cells_Dividing: CL:0000084
            T_regulatory: CL:0000815
    sex: unknown
    ethnicity_ontology_term_id: unknown
    development_stage_ontology_term_id: unknown
uns:
    version:
        corpora_schema_version: 1.0.0
        corpora_encoding_version: 0.0.1
    organism_ontology_term_id: NCBITaxon:9606
    title: scRNA-seq assessment of human lung tissue stability after cold preservation
    layer_descriptions:
        X: scanpy log-transformed and normalized
    contributors:
        - name: Ni Huang
          institution: Sanger Institute
          email: nh3@sanger.ac.uk
    publication_doi:  10.1186/s13059-019-1906-x
    project_name: scRNA-seq assessment of the human lung, spleen, and esophagus tissue stability after cold preservation
    project_description: >
        This study assesses the effect of cold storage on fresh healthy spleen, esophagus, and lung from >= 5
        donors over 72 h. We collect 240,000 high-quality single-cell transcriptomes with detailed cell type annotations and
        whole genome sequences of donors, enabling future eQTL studies. Our data provide a valuable resource for the
        study of these 3 organs and will allow cross-organ comparison of cell types.
        We see little effect of cold ischemic time on cell yield, total number of reads per cell, and other quality control
        metrics in any of the tissues within the first 24 h. However, we observe a decrease in the proportions of lung T cells
        at 72 h, higher percentage of mitochondrial reads, and increased contamination by background ambient RNA reads
        in the 72-h samples in the spleen, which is cell type specific.
    project_links:
        - link_url: https://www.protocols.io/view/cgap-human-spleen-dissociation-tissue-stability-st-32rgqd6
          link_name: CGAP Human Spleen Dissociation - Tissue Stability Study
          link_type: PROTOCOL
        - link_url: https://www.protocols.io/view/cgap-human-lung-dissociation-tissue-stability-stud-34kgquw
          link_name: CGAP Human Lung Dissociation - Tissue Stability Study
          link_type: PROTOCOL
        - link_url: https://www.protocols.io/view/cgap-human-oesophagus-epithelium-dissociation-tiss-34fgqtn
          link_name: CGAP Human Oesophagus Epithelium Dissociation - Tissue Stability
          link_type: PROTOCOL
        - link_url: https://prod.data.humancellatlas.org/explore/projects/c4077b3c-5c98-4d26-a614-246d12c2e5d7
          link_name: Human Cell Atlas
          link_type: RAW_DATA
        - link_url: https://www.tissuestabilitycellatlas.org/
          link_name: Tissue Stability Cell Atlas
          link_type: OTHER
        - link_url: https://www.tissuestabilitycellatlas.org/
          link_name: Tissue Stability Cell Atlas
          link_type: SUMMARY
