obs:
    tissue_ontology_term_id: UBERON:0002370
    assay_ontology_term_id:
        method:
            5GEX: EFO:0009900
            3GEX: EFO:0009899
    disease_ontology_term_id: PATO:0000461
    cell_type_ontology_term_id:
        Anno_level_3:
            B_memory: CL:0000787
            B_naive: CL:0000788
            B_plasma: CL:0000786
            B_pro/pre: CL:0000826
            CD8αα(I): CD8αα(I) T cell
            CD8αα(II): CD8αα(II) T cell
            DC1: CL:0000990
            DC2: CL:0000990 
            DN: CL:0002489
            DP: CL:0000809
            ETP: CL:0000037
            Endo: CL:0000115
            Epi_GCM2: CL:0002293
            Ery: CL:0000232
            Fb_1: CL:0000057
            Fb_2: CL:0000057
            Fb_cycling: CL:0000057
            ILC3: CL:0001071
            Lymph: CL:0002138
            Mac: CL:0000866
            Mast: CL:0000097
            Mgk: CL:0000556
            Mono: CL:0000576
            NK: CL:0000623
            NKT: CL:0000814
            NMP: CL:0000037
            T(agonist): T(agonist)
            TEC(myo): CL:0002293
            TEC(neuro): CL:0002293
            T_memory: CL:0000813
            T_naive: CL:0000898
            Th17: CL:0000899
            Treg: CL:0000815
            Treg(diff): CL:0000815
            VSMC: CL:0000359
            aDC: CL:0000451
            cTEC: CL:0002364
            mTEC: CL:0002365
            pDC: CL:0000784
            γδT: CL:0000798
    sex:
        Gender:
            Male: male
            Female: female
    ethnicity_ontology_term_id: unknowns
    development_stage_ontology_term_id: 
        Age:
            7w: HsapDv:0000037
            8w: HsapDv:0000037
            9w: HsapDv:0000037
            10w: HsapDv:0000037
            11w: HsapDv:0000037
            12w: HsapDv:0000037
            13w: HsapDv:0000037
            14w: HsapDv:0000037
            16w: HsapDv:0000037
            17w: HsapDv:0000037
            3m: HsapDv:0000176
            6m: HsapDv:0000179
            10m: HsapDv:0000183
            15m: HsapDv:0000188
            30m: HsapDv:0000096
            13y: HsapDv:0000107
            24y: HsapDv:0000118
            35y: HsapDv:0000129
uns:
    version:
        corpora_schema_version: 1.0.0
        corpora_encoding_version: 0.0.1
    organism_ontology_term_id: NCBITaxon:9606
    title: A cell atlas of human thymic development defines T cell repertoire formation
    layer_descriptions:
        X: cell ranger 2
    contributors:
        - name: Ni Huang
          institution: Sanger Institute
          email: nh3@sanger.ac.uk
    publication_doi: https://doi.org/10.1126/science.aay3224
    project_name: A cell atlas of human thymic development defines T cell repertoire formation
    project_description: >
        The thymus provides a nurturing environment for the differentiation and selection of T cells,
        a process orchestrated by their interaction with multiple thymic cell types. We used single-cell
        RNA sequencing to create a cell census of the human thymus across the life span and to reconstruct
        T cell differentiation trajectories and T cell receptor (TCR) recombination kinetics. Using this
        approach, we identified and located in situ CD8αα+ T cell populations, thymic fibroblast subty
        and activated dendritic cell states. In addition, we reveal a bias in TCR recombination a
        selection, which is attributed to genomic position and the kinetics of lineage commitment. Taken
        together, our data provide a comprehensive atlas of the human thymus across the life span with
        new insights into human T cell development.
    project_links:
        - link_name: ArrayExpress
          link_url: https://www.ebi.ac.uk/arrayexpress/experiments/E-MTAB-8581/
          link_type: RAW_DATA
        - link_name: Development Cell Atlas
          link_url: https://developmentcellatlas.ncl.ac.uk/
          link_type: OTHER
        - link_name: Development Cell Atlas
          link_url: https://developmentcellatlas.ncl.ac.uk/
          link_type: SUMMARY
