Description: >
  This deploys a Coropora data portal remote-dev environment
Parameters:
  ImageTag:
    Description: Please provide an image tag
    Type: String

Resources:
  DevEnv:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://happy-cf.s3.us-west-2.amazonaws.com/dp-entrypoint_dev.yml
      Parameters:
        CustomStackName: !Ref AWS::StackName
        ImageTag: !Ref ImageTag

Outputs:
  FrontendUrl:
    Description: The URL endpoint for the website service
    Value: !GetAtt DevEnv.Outputs.FrontendUrl
  BackendUrl:
    Description: The URL endpoint for the website service
    Value: !GetAtt DevEnv.Outputs.BackendUrl
