obs:
    tissue_ontology_term_id:
    assay_ontology_term_id: 
    disease_ontology_term_id: 
    cell_type_ontology_term_id:
    sex: 
    ethnicity_ontology_term_id: 
    development_stage_ontology_term_id: 
uns:
    version:
        corpora_schema_version:
        corpora_encoding_version:
    organism_ontology_term_id: 
    title: 
    layer_descriptions:
    contributors:
    publication_doi: 
    preprint_doi: 
    project_name: 
    project_description: 
    project_links: []
