name: linter
on: [pull_request]
jobs:
  flake8:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Python Code Quality and Lint
        uses: ./.github/actions/flake8
        with:
          args: .
