name: linter
on: [push]
jobs:
  flake8-black-mypy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Python Code Quality and Lint
        uses: ricardochaves/python-lint@v1.1.0
        with:
          python-root-list: "."
          use-pylint: false
          use-pycodestyle: false
          use-flake8: true
          use-black: true
          use-mypy: true
          use-isort: false
