name: CI

on: [pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run linter
      run: |
        pip install yapf
        yapf --recursive --diff .
