name: CI

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run linter
        run: |
          pip install yapf
          cd $GITHUB_WORKSPACE
          yapf --recursive --diff --verbose.
        shell: bash
