name: "Scale test api (via cloudfront)"

on:
  schedule:
    - cron: "0 0 * * Sun"

jobs:
  locust-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Install dependencies
        run: |
          pip install -r tests/scale/requirements-scale.txt
      - name: Dev Scale Test
        run: |
          locust -f tests/scale/scale_test_portal_apis.py --headless -u 30 -r 10 --host https://api.cellxgene.dev.single-cell.czi.technology/ --run-time 5m 2>&1 | tee locust_dev_stats.txt
      - name: Slack success webhook
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        run: |
          DEV_STATS=$(tail -n 13 locust_dev_stats.txt)
          DEV_MSG="\`\`\`DEV SCALE TEST RESULTS: ${DEV_STATS}\`\`\`"
          curl -X POST -H 'Content-type: application/json' --data "{'text':'${DEV_MSG}'}" $SLACK_WEBHOOK


